/**
 * Sample CLI Script for Testing Credential Issuance
 * 
 * This script demonstrates how to request a Verifiable Credential from the issuer service.
 * It calls the /issue endpoint with sample DID and claims data, then displays the returned VC.
 * 
 * USAGE:
 * 1. Ensure the issuer service is running: npm start
 * 2. Run this script: node scripts/issue-sample.js
 * 
 * PREREQUISITES:
 * - Issuer service must be running on http://localhost:8080
 * - The service must have successfully initialized the issuer DID
 * 
 * CUSTOMIZATION:
 * - Modify SAMPLE_DID to use your own holder DID
 * - Modify SAMPLE_CLAIMS to include your own credential claims
 * - Change ISSUER_URL if your service runs on a different port
 */

const ISSUER_URL = process.env.ISSUER_URL || 'http://localhost:8080';

// Sample holder DID (did:key format)
// In a real scenario, this would be generated by the holder's wallet/client
const SAMPLE_DID = 'did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK';

// Sample claims for document ownership credential
// These would typically include storage keys from R2 uploads
const SAMPLE_CLAIMS = {
  storageKey: 'sample-encrypted-doc-abc123.pdf',
  docType: 'passport',
  uploadTimestamp: new Date().toISOString(),
  documentHash: '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef'
};

/**
 * Request a Verifiable Credential from the issuer service
 */
async function issueCredential() {
  console.log('='.repeat(60));
  console.log('DID Credential Vault - Sample Credential Issuance');
  console.log('='.repeat(60));
  console.log();

  console.log('Requesting credential from issuer...');
  console.log(`Issuer URL: ${ISSUER_URL}/issue`);
  console.log(`Subject DID: ${SAMPLE_DID}`);
  console.log('Claims:', JSON.stringify(SAMPLE_CLAIMS, null, 2));
  console.log();

  try {
    // Make POST request to /issue endpoint
    const response = await fetch(`${ISSUER_URL}/issue`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        subjectDid: SAMPLE_DID,
        claims: SAMPLE_CLAIMS
      })
    });

    // Check if request was successful
    if (!response.ok) {
      const errorData = await response.json();
      console.error('❌ Credential issuance failed!');
      console.error('Status:', response.status);
      console.error('Error:', JSON.stringify(errorData, null, 2));
      process.exit(1);
    }

    // Parse and display the returned VC
    const data = await response.json();
    
    console.log('✅ Credential issued successfully!');
    console.log();
    console.log('='.repeat(60));
    console.log('VERIFIABLE CREDENTIAL (formatted JSON):');
    console.log('='.repeat(60));
    console.log();
    console.log(JSON.stringify(data.vc, null, 2));
    console.log();
    console.log('='.repeat(60));
    console.log('Credential Details:');
    console.log('='.repeat(60));
    
    // Extract and display key information from the VC
    const vc = data.vc;
    console.log(`Type: ${vc.type ? vc.type.join(', ') : 'N/A'}`);
    console.log(`Issuer: ${vc.issuer?.id || vc.issuer || 'N/A'}`);
    console.log(`Subject: ${vc.credentialSubject?.id || 'N/A'}`);
    console.log(`Issuance Date: ${vc.issuanceDate || 'N/A'}`);
    console.log(`Proof Format: ${vc.proof?.type || 'JWT'}`);
    console.log();
    
    console.log('✨ You can now use this credential to:');
    console.log('   1. Store it in the encrypted vault (client application)');
    console.log('   2. Create a Verifiable Presentation for verification');
    console.log('   3. Share it with verifiers to prove document ownership');
    console.log();

  } catch (error) {
    console.error('❌ Error occurred during credential issuance:');
    console.error(error.message);
    
    if (error.code === 'ECONNREFUSED') {
      console.error();
      console.error('⚠️  Connection refused. Please ensure:');
      console.error('   1. The issuer service is running (npm start)');
      console.error('   2. The service is accessible at', ISSUER_URL);
    }
    
    process.exit(1);
  }
}

// Run the script
issueCredential();
